name: Docs

on:
  push:
    branches:
      -  main

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'cmd420/rust-ore'

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Create documentation
        run: cargo doc --document-private-items

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: target/doc
          clean: true
          commit-message: "Update docs"